# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmdoc < Formula
  desc "Analyze and fix Helm charts"
  homepage "https://github.com/belyaev-dev/helmdoc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_darwin_amd64.zip"
      sha256 "6ca61a5495f973cd18e45bbcbf00c93cd8831f531ce23217a23077e034e53e5b"

      define_method(:install) do
        bin.install "helmdoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_darwin_arm64.zip"
      sha256 "5d5cbf28fa04a7acb2b27b3d44c589536083538f7070be40db4d00895dd98853"

      define_method(:install) do
        bin.install "helmdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_linux_amd64.zip"
      sha256 "9277dcb19d6aca75589c82b647fb6d5727c79e662ac3dd0ae5c836ecdab67f45"
      define_method(:install) do
        bin.install "helmdoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_linux_arm64.zip"
      sha256 "8b307d7dbbb049a3c2584a239b2d6e8605cbb22b0668799dceb146cc771a8408"
      define_method(:install) do
        bin.install "helmdoc"
      end
    end
  end

  test do
    system "#{bin}/helmdoc", "version"
  end
end
