# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmdoc < Formula
  desc "Analyze and fix Helm charts"
  homepage "https://github.com/belyaev-dev/helmdoc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_darwin_amd64.zip"
      sha256 "f64d0a263f7b6a27c080f317281e8a36ebdb0553ddeb256a88062e7d9878ee2f"

      define_method(:install) do
        bin.install "helmdoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_darwin_arm64.zip"
      sha256 "f9a90dcf62f581cd985ec0e79cba05a0485967f7c6a3f1b5fa890e3fdc246beb"

      define_method(:install) do
        bin.install "helmdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_linux_amd64.zip"
      sha256 "f949d771bfdb0a670d3a2fd4bdcfeb5933815d6ce6bdd52e2e98d1e8f4069067"
      define_method(:install) do
        bin.install "helmdoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_linux_arm64.zip"
      sha256 "206959a081a4056d8b73e13a95418257e6ba63f126f350043c0fc8d3abc4813b"
      define_method(:install) do
        bin.install "helmdoc"
      end
    end
  end

  test do
    system "#{bin}/helmdoc", "version"
  end
end
