# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helmdoc < Formula
  desc "Production-readiness linter for Helm charts"
  homepage "https://github.com/belyaev-dev/helmdoc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_darwin_amd64.tar.gz"
      sha256 "5afcab17303bd768ab6f4c9bf06697255d9007d70a33ae63172af53b3c4be38d"

      define_method(:install) do
        bin.install "helmdoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_darwin_arm64.tar.gz"
      sha256 "62369c741581e7838999b9db3f1dac9f2a2d31075f16ac2d009ff78ece857482"

      define_method(:install) do
        bin.install "helmdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_linux_amd64.tar.gz"
      sha256 "4023d38774aa01de17dac06132b280d98c5cdfe95184ca689df0608c683c12c0"
      define_method(:install) do
        bin.install "helmdoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/belyaev-dev/helmdoc/releases/download/v0.1.0/helmdoc_0.1.0_linux_arm64.tar.gz"
      sha256 "ae42185dec2606991efb5eeff86b88ba7407c5618e322b9ffd1244b95eea80c5"
      define_method(:install) do
        bin.install "helmdoc"
      end
    end
  end

  test do
    system "#{bin}/helmdoc", "version"
  end
end
